version: "3.8"
services:
    document-front:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: document-front
        environment:
            VUE_APP_BASE_API: "http://68.183.212.124:3000/"
        ports:
            - "3000:8080"
        volumes:
            - ./app
